export class Register{

    constructor(
        public id:number=0,
        public nationalID:string="",
        public imageID:string="",
        public fullname:string="",
        public studyYear:string="",
        public studyClass:string="",
        public studySession:string="",
        public nationality:string="",
        public hBirthdate:string="",
        public mBirthdate:string="",
        public birthNation:string="",
        public kindgarten:string="true",
        public idenType:string="",
        public idenNumber:string="",
        public idenSource:string="",
        public idenDate:string="",
        public idenExpireDate:string="",
        public fromSchool:string="",
        public transferDate:string="",
        public studentStatus:string="",
        public parentFullname:string="",
        public relativeType:string="",
        public parentNation:string="",
        public motherNation:string="",
        public parentIdenType:string="",
        public parentIdenNumber:string="",
        public parentIdenSource:string="",
        public parentIdenExpir:string="",
        public parentCity:string="",
        public parentStreet:string="",
        public parentPhone:string="",
        public parentEmail:string="",
        public parentJopAddress:string="",
        public parentJobPhone:string="",
        public relativename:string="",
        public relativePhone:string="",
        public mothername:string="",
        public motherPhone:string="",
        public housewife:string="نعم",
        public motherJobAddress:string="",
        public studentAddress:string="",
        public password:string=""
    ){}

}